version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 12

  build:
    commands:
    - pwd
    - PROJECT_DIR=$(pwd)
    - echo $PROJECT_DIR
    - ls -rtl
    - chmod -R 755 *
    - echo "Running angular build"
    - ls -rtl
    - cd good-people-angular && npm install && npm install @angular/cli && npm run ng build --prod=true --outputPath=../src/main/resources/static
    - ls -rtl
    - cd ..
    - echo "Checking angular output location"
    - ls -rtl
    - ls -rtl **/*
    - ls -rtl src/main/resources/static
    - echo "Running gradle build"
    - ls -rtl
    - ./gradlew createDist
    - echo "Done gradle createDist"
    - ls -rtl

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - service.war