version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 12

  build:
    commands:
    - pwd
    - ls -rtl
    - chmod -R 755 *
    - echo "Running angular build"
    - ls -rtl
    - cd good-people-angular && npm install && npm install @angular/cli && npm run ng build --prod=true --outputPath=../src/main/resources/static
    - echo "Running gradle build"
    - ls -rtl
    - ../gradlew createDist

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - service.war