version: 0.2

phases:
  build:
    commands:
    - pwd
    - ls -rtl
    - chmod 755 *
    - ./gradlew createDist

artifacts:
  files:
    - deployment/appspec.yml
    - build/dist.zip
  discard-paths: yes