version: 0.0
os: linux
files:
- source: service.war
  destination: /var/opt/apps/good-people/source
hooks:
  BeforeInstall:
  - location: scripts/stop_service.sh
  - location: scripts/clear_payload.sh
  AfterInstall:
  - location: scripts/deploy_service.sh
  ApplicationStart:
  - location: scripts/run_service.sh
    timeout: 3600
  ValidateService:
  - location: scripts/check_service.sh
    timeout: 3600